In [1]:
import networkx as nx
import torch
import torch_geometric
from torch_geometric.datasets import WikipediaNetwork
from torch_geometric.utils import to_networkx
from torch_geometric.utils import k_hop_subgraph
from atten_layer import ATLayer


In [2]:
dataset = WikipediaNetwork(root="/home/siddy/META/data", name='chameleon')
data = dataset[0]

In [3]:
data

Data(x=[2277, 2325], edge_index=[2, 36101], y=[2277], train_mask=[2277, 10], val_mask=[2277, 10], test_mask=[2277, 10])

In [4]:
x = data.x

In [5]:
data.edge_index

tensor([[   0,    0,    0,  ..., 2276, 2276, 2276],
        [1161, 1667, 1991,  ..., 2212, 2246, 2276]])

In [6]:
edge_index = data.edge_index

In [7]:
G = to_networkx(data, to_undirected=True)

In [8]:
y= data.y

In [9]:
paths = nx.single_source_shortest_path(G, 0, cutoff=2)

In [10]:
paths

{0: [0],
 1161: [0, 1161],
 1667: [0, 1667],
 1991: [0, 1991],
 2130: [0, 2130],
 2156: [0, 2156],
 128: [0, 1161, 128],
 275: [0, 1161, 275],
 359: [0, 1161, 359],
 431: [0, 1161, 431],
 472: [0, 1161, 472],
 725: [0, 1161, 725],
 815: [0, 1161, 815],
 1044: [0, 1161, 1044],
 1125: [0, 1161, 1125],
 2162: [0, 1161, 2162],
 2246: [0, 1161, 2246],
 1611: [0, 1667, 1611],
 320: [0, 1991, 320],
 1181: [0, 2130, 1181],
 1620: [0, 2130, 1620],
 1878: [0, 2130, 1878],
 1914: [0, 2130, 1914],
 2149: [0, 2130, 2149],
 2263: [0, 2130, 2263]}

In [11]:
edge_list= []
for key, value in paths.items():
    print(value)
    if len(value)==2:
        edge_list.append(value)
    elif len(value)==3:
        edge_list.append(value[1:])
    

[0]
[0, 1161]
[0, 1667]
[0, 1991]
[0, 2130]
[0, 2156]
[0, 1161, 128]
[0, 1161, 275]
[0, 1161, 359]
[0, 1161, 431]
[0, 1161, 472]
[0, 1161, 725]
[0, 1161, 815]
[0, 1161, 1044]
[0, 1161, 1125]
[0, 1161, 2162]
[0, 1161, 2246]
[0, 1667, 1611]
[0, 1991, 320]
[0, 2130, 1181]
[0, 2130, 1620]
[0, 2130, 1878]
[0, 2130, 1914]
[0, 2130, 2149]
[0, 2130, 2263]


In [12]:
edge_list

[[0, 1161],
 [0, 1667],
 [0, 1991],
 [0, 2130],
 [0, 2156],
 [1161, 128],
 [1161, 275],
 [1161, 359],
 [1161, 431],
 [1161, 472],
 [1161, 725],
 [1161, 815],
 [1161, 1044],
 [1161, 1125],
 [1161, 2162],
 [1161, 2246],
 [1667, 1611],
 [1991, 320],
 [2130, 1181],
 [2130, 1620],
 [2130, 1878],
 [2130, 1914],
 [2130, 2149],
 [2130, 2263]]

In [22]:
size = len(set([n for e in edge_list for n in e]))
size

25

In [23]:
adj_matrix = torch.zeros(size, size)
adj_matrix.shape

torch.Size([25, 25])

In [18]:
# nodes must be numbers in a sequential range starting at 0 - so this is the
# number of nodes. you can assert this is the case as well if desired 
size = len(set([n for e in edge_list for n in e])) 
# make an empty adjacency list  
adjacency = [[0]*size for _ in range(size)]
print(adjacency.shape)
# populate the list for each edge
#for sink, source in edge_list:
#    adjacency[sink][source] = 1


AttributeError: 'list' object has no attribute 'shape'

In [21]:
E = [[0, 0], [0, 1], [1, 0], [1, 1]]

# nodes must be numbers in a sequential range starting at 0 - so this is the
# number of nodes. you can assert this is the case as well if desired 
size = len(set([n for e in E for n in e])) 
print(size)
# make an empty adjacency list  
adjacency = [[0]*size for _ in range(size)]
print(len(adjacency))
# populate the list for each edge
for sink, source in E:
    adjacency[sink][source] = 1

2
2


In [20]:
adjacency

[[1, 1], [1, 1]]

In [17]:
edge_list = torch.permute(torch.tensor(edge_list, dtype=torch.long),(1,0))

In [18]:
edge_list

tensor([[   0,    0,    0,    0,    0, 1161, 1161, 1161, 1161, 1161, 1161, 1161,
         1161, 1161, 1161, 1161, 1667, 1991, 2130, 2130, 2130, 2130, 2130, 2130],
        [1161, 1667, 1991, 2130, 2156,  128,  275,  359,  431,  472,  725,  815,
         1044, 1125, 2162, 2246, 1611,  320, 1181, 1620, 1878, 1914, 2149, 2263]])

In [19]:
edge_list.shape

torch.Size([2, 24])

In [69]:
from torch_geometric.data import Data

In [ ]:
    E= [[0, 0], [0, 1], [1, 0], [1, 1]]
    size = max(max(E))+1
    r = [[0 for i in range(size)] for j in range(size)]
    for row,col in E:
        r[row][col] = 1
    print(r) 

In [23]:
edge_list= edge_list.reshape(-1, 2)

In [25]:
edge_list

tensor([[   0,    0],
        [   0,    0],
        [   0, 1161],
        [1161, 1161],
        [1161, 1161],
        [1161, 1161],
        [1161, 1161],
        [1161, 1161],
        [1667, 1991],
        [2130, 2130],
        [2130, 2130],
        [2130, 2130],
        [1161, 1667],
        [1991, 2130],
        [2156,  128],
        [ 275,  359],
        [ 431,  472],
        [ 725,  815],
        [1044, 1125],
        [2162, 2246],
        [1611,  320],
        [1181, 1620],
        [1878, 1914],
        [2149, 2263]])

In [28]:
size = len(set([n for e in edge_list for n in e])) 

In [29]:
size

48

In [72]:
data = Data(x=x, edge_index=edge_list, y=y)

In [73]:
data

Data(x=[2277, 2325], edge_index=[2, 24], y=[2277])

In [75]:
data.x.shape

torch.Size([2277, 2325])